global using System.Security.Claims;
global using System.Text;
global using System.IdentityModel.Tokens.Jwt;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using SharedX.Abstractions.GatewayScopes;
global using Gateway.Common;
global using Gateway.InternalAuth;
global using Carter;
global using static Gateway.Common.Constants;